Repository dnd-side-project/dnd-12th-6-frontend, pull requests merged in 2025-02, with the labels that each got.

#5 #3 test setting
  .husky/.gitignore
  .husky/pre-commit
  .lintstagedrc.json
  jest.config.ts
  jest.setup.ts
  package.json
  pnpm-lock.yaml
  src/__test__/index.test.ts
  src/app/page.tsx
  src/components/common/Button/index.tsx
  src/components/common/Input/Input.stories.tsx
  src/components/common/Input/index.tsx
Labels: 🔧 Chore, ✅ Test

#11 #6 define design system, add font files
  README.md
  public/fonts/NEXON_Lv1_Gothic_OTF_Bold.otf
  src/styles/globals.css
  tailwind.config.ts
Labels: 🔧 Chore, ✨ Feat, 🎨 Style, 🖥️ Frontend

#13 #12 Layout style add & font fix
  package.json
  pnpm-lock.yaml
  src/app/favicon.ico
  src/app/fonts/GeistMonoVF.woff
  src/app/fonts/GeistVF.woff
  src/app/layout.tsx
  src/app/page.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feat, 🎨 Style

#17 #16 Tab Component UI & Storybook
  src/components/common/Tab/Tab.stories.tsx
  src/components/common/Tab/index.tsx
  src/components/common/Tab/modules/TabContext.tsx
  src/components/common/Tab/ui/TabCount.tsx
  src/components/common/Tab/ui/TabMain.tsx
  src/components/common/Tab/ui/TabText.tsx
  src/styles/theme/index.ts
  src/styles/theme/spacing.ts
  tailwind.config.ts
Labels: ✨ Feat, 🎨 Style, ✅ Test, 🖥️ Frontend

#18 #7 BottomNav, Header 컴포넌트 구현 및 적용
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/page.tsx
  src/components/layout/BottomNav/BottomNav.stories.tsx
  src/components/layout/BottomNav/index.tsx
  src/components/layout/BottomNav/ui/BottomNavItem.tsx
  src/components/layout/BottomNav/ui/BottomNavMain.tsx
  src/components/layout/Header/index.tsx
  src/components/layout/PageContainer/index.tsx
  src/store/bottomNavStore.ts
  src/types/common.ts
  tailwind.config.ts
Labels: ✨ Feat, 🎨 Style, ✅ Test, 🖥️ Frontend

#25 #9 카드 모듈 컴포넌트 작업
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/images/card/01-Envelope-Default Type.png
  public/images/card/02-Envelope-Card Type.png
  public/images/module/01-Card-Module.png
  public/images/sticker/01-Sticker-L.png
  public/images/sticker/01-Sticker-Module.png
  public/images/sticker/01-Sticker-R.png
  public/images/sticker/02-Sticker-L.png
  public/images/sticker/02-Sticker-R.png
  public/images/sticker/03-Sticker-Module.png
  src/app/page.tsx
  src/components/common/Card/Card.stories.tsx
  src/components/common/Card/index.tsx
  src/components/common/Card/layout/CardScroller.stories.tsx
  src/components/common/Card/layout/CardScroller.tsx
  src/components/common/Card/modules/CardDataFetcher.tsx
  src/components/common/Card/ui/CardBody.tsx
  src/components/common/Card/ui/CardContainer.tsx
  src/components/common/Card/ui/CardFooter.tsx
  src/components/common/Card/ui/CardHeader.tsx
  src/utils/format/formatDate.ts
  tailwind.config.ts
Labels: ✨ Feat, 🎨 Style, ✅ Test, 🖥️ Frontend

#24 #21 Field & Input 컴포넌트 작업
  package.json
  src/components/common/Field/Field.stories.tsx
  src/components/common/Field/index.tsx
  src/components/common/Field/ui/FieldHelpText.tsx
  src/components/common/Field/ui/FieldLabel.tsx
  src/components/common/Field/ui/FieldMain.tsx
  src/components/common/Icon/lib/error_icon.svg
  src/components/common/Icon/lib/index.ts
  src/components/common/Input/Input.stories.tsx
  src/components/common/Input/index.tsx
  src/styles/theme/index.ts
  src/styles/theme/typography.ts
  tailwind.config.ts
Labels: 🎨 Style, ✅ Test, 🖥️ Frontend

#27 Test Deployment 1.0.0
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/images/card/01-Envelope-Default Type.png
  public/images/card/02-Envelope-Card Type.png
  public/images/module/01-Card-Module.png
  public/images/sticker/01-Sticker-L.png
  public/images/sticker/01-Sticker-Module.png
  public/images/sticker/01-Sticker-R.png
  public/images/sticker/02-Sticker-L.png
  public/images/sticker/02-Sticker-R.png
  public/images/sticker/03-Sticker-Module.png
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Card/Card.stories.tsx
  src/components/common/Card/index.tsx
  src/components/common/Card/layout/CardScroller.stories.tsx
  src/components/common/Card/layout/CardScroller.tsx
  src/components/common/Card/modules/CardDataFetcher.tsx
  src/components/common/Card/ui/CardBody.tsx
  src/components/common/Card/ui/CardContainer.tsx
  src/components/common/Card/ui/CardFooter.tsx
  src/components/common/Card/ui/CardHeader.tsx
  src/components/common/Field/Field.stories.tsx
  src/components/common/Field/index.tsx
  src/components/common/Field/ui/FieldHelpText.tsx
  src/components/common/Field/ui/FieldLabel.tsx
  src/components/common/Field/ui/FieldMain.tsx
  src/components/common/Icon/lib/error_icon.svg
  src/components/common/Icon/lib/index.ts
  src/components/common/Input/Input.stories.tsx
  src/components/common/Input/index.tsx
  src/components/layout/BottomNav/BottomNav.stories.tsx
  src/components/layout/BottomNav/index.tsx
  src/components/layout/BottomNav/ui/BottomNavItem.tsx
  src/components/layout/BottomNav/ui/BottomNavMain.tsx
  src/components/layout/Header/index.tsx
  src/components/layout/PageContainer/index.tsx
  src/store/bottomNavStore.ts
  src/styles/theme/index.ts
  src/styles/theme/typography.ts
  src/types/common.ts
  src/utils/format/formatDate.ts
  tailwind.config.ts
Labels: 🔧 Chore, 🖥️ Frontend

#33 Refactor/Input 컴포넌트 스타일 수정 & NumberInput 추가
  pnpm-lock.yaml
  src/components/common/Field/Field.stories.tsx
  src/components/common/Field/index.tsx
  src/components/common/Field/ui/FieldLabel.tsx
  src/components/common/Icon/lib/check_circle_icon.svg
  src/components/common/Icon/lib/index.ts
  src/components/common/Icon/lib/minus_icon.svg
  src/components/common/Icon/lib/plus_icon.svg
  src/components/common/Input/Input.stories.tsx
  src/components/common/Input/index.ts
  src/components/common/Input/ui/Input.tsx
  src/components/common/Input/ui/InputMain.tsx
  src/components/common/NumberInput/index.tsx
  src/styles/globals.css
Labels: ✨ Feat, 🎨 Style, ✅ Test, 🖥️ Frontend

#34 #32 Tanstack query, 카카오 로그인 연결
  .gitignore
  package.json
  src/api/customFetch.ts
  src/api/endpoint.ts
  src/api/index.ts
  src/app/auth/kakao/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/lib/auth/index.ts
  src/lib/auth/types.ts
  src/store/authStore.ts
  src/utils/query/provider.tsx
Labels: 🔧 Chore, ✨ Feat, 🖥️ Frontend

#38 #37 useSearchParams 사용한 페이지에 Suspense 추가
  pnpm-lock.yaml
  src/app/auth/kakao/layout.tsx
  src/app/auth/kakao/page.tsx
Labels: 🐛 Fix

#35 #31 초대장 목록 페이지 UI, 카드 무한 스크롤 UI 구현
  .env
  package.json
  pnpm-lock.yaml
  src/app/list/page.tsx
  src/components/common/Card/layout/CardList.stories.tsx
  src/components/common/Card/layout/CardList.tsx
  src/components/common/Card/modules/InfiniteCardFetcher.tsx
  src/components/common/Icon/lib/index.ts
  src/components/common/Icon/lib/invite_empty.svg
  src/components/common/Tab/ui/TabCount.tsx
  src/components/common/Tab/ui/TabText.tsx
  src/components/layout/BottomNav/ui/BottomNavItem.tsx
  src/components/layout/PageContainer/index.tsx
  src/components/list/InvitationList/index.tsx
  src/components/list/InvitationTabs/index.tsx
  src/store/invitationListStore.ts
Labels: ✨ Feat, 🎨 Style, ✅ Test, 🖥️ Frontend

#42 #41 Date 모달 캘린더 UI 수정 및 데이터 바인딩
  src/app/create/components/CreateForm.tsx
  src/components/common/BottomSheet/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Calendar/index.tsx
  src/components/common/Card/ui/CardFooter.tsx
  src/components/common/DateInput/DatePickerArea.tsx
  src/components/common/DateInput/DateTimeArea.tsx
  src/components/common/DateInput/index.tsx
  src/components/common/Icon/lib/index.ts
  src/components/common/Icon/lib/time_icon.svg
  src/utils/format/formatDate.ts
Labels: ♻️ Refactoring, 🖥️ Frontend

#48 #45 초대장 관리 UI 작업
  public/images/response/message_background.png
  src/app/invitation/manage/[id]/page.tsx
  src/components/common/Icon/lib/edit_icon.svg
  src/components/common/Icon/lib/index.ts
  src/components/common/Icon/lib/location_history_icon.svg
  src/components/common/Icon/lib/time_history_icon.svg
  src/components/common/Icon/lib/user_history_icon.svg
  src/components/common/Icon/lib/view_icon.svg
  src/components/manage/Invitation/index.tsx
  src/components/manage/Response/ResponseContent.tsx
  src/components/manage/Response/ResponseTab.tsx
  src/components/manage/Response/index.tsx
  src/utils/format/formatDate.ts
  tailwind.config.ts
Labels: ✨ Feat, 🎨 Style, 🖥️ Frontend

#51 #45 초대장 관리 UI 추가 작업, 모달, CopyLinkWithAlert 컴포넌트 추가
  public/images/etc/kakao_symbol.png
  public/images/etc/kakao_symbol_primary.png
  src/app/create/@modal/(.)card/page.tsx
  src/app/create/components/PreviewBox.tsx
  src/app/invitation/manage/[id]/cancel/page.tsx
  src/components/common/CopyLinkWithAlert/CopyLinkWithAlert.stories.tsx
  src/components/common/CopyLinkWithAlert/index.tsx
  src/components/common/CopyLinkWithAlert/useCopyLink.ts
  src/components/common/Dialog/dialog.tsx
  src/components/common/Icon/lib/index.ts
  src/components/common/Icon/lib/invite_cancel_icon.svg
  src/components/common/Icon/lib/link_icon.svg
  src/components/manage/Invitation/index.tsx
  src/components/manage/Response/CancelModal/CancelModal.stories.tsx
  src/components/manage/Response/CancelModal/index.tsx
  src/components/manage/Response/DeleteModal/DeleteModal.stories.tsx
  src/components/manage/Response/DeleteModal/index.tsx
  src/components/manage/Response/ShareModal/ShareModal.stories.tsx
  src/components/manage/Response/ShareModal/index.tsx
  src/components/manage/Response/index.tsx
  tailwind.config.ts
Labels: ✨ Feat, 🎨 Style, ✅ Test, 🖥️ Frontend

#54 #53 API 코드 세팅
  src/__mock__/data.ts
  src/api/customFetch.ts
  src/api/endpoint.ts
  src/api/index.ts
  src/api/types.ts
  src/app/auth/kakao/page.tsx
  src/components/common/Card/Card.stories.tsx
  src/components/common/Card/index.tsx
  src/components/common/Card/layout/CardList.stories.tsx
  src/components/common/Card/layout/CardList.tsx
  src/components/common/Card/layout/CardScroller.stories.tsx
  src/components/common/Card/layout/CardScroller.tsx
  src/components/common/Card/modules/CardDataFetcher.tsx
  src/components/common/Card/modules/InfiniteCardFetcher.tsx
  src/components/common/Card/ui/CardBody.tsx
  src/components/common/Card/ui/CardContainer.tsx
  src/components/common/Card/ui/CardFooter.tsx
  src/components/common/Card/ui/CardHeader.tsx
  src/components/login/KakaoLogin.tsx
  src/lib/auth/cookie.ts
  src/lib/invitation/hooks/useGetReceivedInvitationsQuery.ts
  src/lib/invitation/hooks/useGetSentInvitationsQuery.ts
  src/lib/invitation/index.ts
  src/lib/invitation/keys.ts
  src/lib/invitation/types.ts
Labels: 🔧 Chore, 🐛 Fix, 🖥️ Frontend

#56 #52 초대장 생성 API 연동
  package.json
  pnpm-lock.yaml
  src/app/create/components/CreateForm.tsx
  src/app/create/components/PreviewBox.tsx
  src/app/layout.tsx
  src/components/card/CardContainer.tsx
  src/components/card/CardSelect/SelectContent/BackgroundSelect.tsx
  src/components/card/CardSelect/SelectContent/UploadBackgroundButton.tsx
  src/components/card/PageHeaderButton.tsx
  src/components/common/NumberInput/index.tsx
  src/components/common/Toast/toast.tsx
  src/components/common/Toast/toaster.tsx
  src/hooks/useToast.ts
  src/lib/invitation/types.ts
  src/store/invitationStore.ts
  tailwind.config.ts
Labels: ✨ Feat, ♻️ Refactoring, 🖥️ Frontend

#59 #44 og 이미지 동적 생성 및 meta tag 추가
  next.config.mjs
  public/favicon.svg
  public/opengraph.png
  src/app/invite/[id]/opengraph-image.tsx
  src/app/layout.tsx
  src/components/card/CardDisplay/index.tsx
Labels: ✨ Feat, 🖥️ Frontend
